sudo: required
services:
  - docker

before_install:
  - docker build -t benwrighthd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run benwrighthd/react-test yarn test -- --coverage

after_success:
  - docker build -t benwrighthd/multi-client ./client
  - docker build -t benwrighthd/multi-nginx ./nginx
  - docker build -t benwrighthd/multi-server ./server
  - docker build -t benwrighthd/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push benwrighthd/multi-client
  - docker push benwrighthd/multi-nginx
  - docker push benwrighthd/multi-server
  - docker push benwrighthd/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-051122044027
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
